local State = {
	-- Universal
	Idle = "idle",
	Attacking = "attacking",
	AttackingHeavy = "attackingHeavy",
	Casting = "casting",
	SoulCasting = "soulcasting",
	Sprinting = "sprinting",
	Walking = "walking",
	Jumping = "jumping",
	Blocking = "blocking",
	Dashing = "dashing",
	InAirCombo = "inaircombo",
	Stunned = "stunned",
	Dead = "dead",
	Endlag = "endlag",
	Ragdolled = "ragdolled",
	Hyperarmor = "hyperarmor",
	Knocked = "knocked",

	-- AI states
	Chasing = "chasing",
}

return State
