return {
	hp = 1000,
	energy = 100,
	durability = 10,
	attackDmg = 20,
	magicDmg = 20,
	attackSpeed = 1,
	attackCooldown = 0.45,
	attackHeavyCooldown = 2,
	critChance = 0.25,
	critMultiplier = 1.75,
	pierce = 0,
	speed = 12,
	range = 5,

	ranged = false,
	attackDmgType = "physical",

	abilities = {
		[1] = "Flamethrower",

		[2] = "Matrix Uplink",

		[3] = "Seismic Slam",

		[4] = "Overdrive",
	},
	cooldowns = {
		[1] = 5,

		[2] = 5,

		[3] = 5,

		[4] = 5,
	},
}
