return {
	attacking = {
		hp = 1000,
		energy = 100,
		durability = 10,
		attackDmg = 20,
		magicDmg = 20,
		attackSpeed = 1,
		attackCooldown = 0.45,
		critChance = 0.25,
		critMultiplier = 1.75,
		pierce = 0,
		speed = 12,
		range = 5,
		soulType = "Engage",

		ranged = false,
		attackDmgType = "physical",

		abilities = {
			[1] = "Fireball",

			[2] = "Counter",

			[3] = "Barrage",

			[4] = "Ice",
		},
		cooldowns = {
			[1] = 5,

			[2] = 5,

			[3] = 5,

			[4] = 5,
		},
	},
	blocking = {
		hp = 1000,
		energy = 100,
		durability = 10,
		attackDmg = 20,
		magicDmg = 20,
		attackSpeed = 1,
		attackCooldown = 0.45,
		critChance = 0.25,
		critMultiplier = 1.75,
		pierce = 0,
		speed = 12,
		range = 5,
		soulType = "Engage",

		ranged = false,
		attackDmgType = "physical",

		abilities = {
			[1] = "Fireball",

			[2] = "Counter",

			[3] = "Barrage",

			[4] = "Ice",
		},
		cooldowns = {
			[1] = 5,

			[2] = 5,

			[3] = 5,

			[4] = 5,
		},
	},
	uptilt = {
		hp = 1000,
		energy = 100,
		durability = 10,
		attackDmg = 20,
		magicDmg = 20,
		attackSpeed = 1,
		attackCooldown = 0.45,
		critChance = 0.25,
		critMultiplier = 1.75,
		pierce = 0,
		speed = 12,
		range = 5,
		soulType = "Engage",

		ranged = false,
		attackDmgType = "physical",

		abilities = {
			[1] = "Fireball",

			[2] = "Counter",

			[3] = "Barrage",

			[4] = "Ice",
		},
		cooldowns = {
			[1] = 5,

			[2] = 5,

			[3] = 5,

			[4] = 5,
		},
	},
}
